#!/bin/bash

cd "$(dirname "$0")"

declare -A REMOTES
REMOTES=([doobry]='https://github.com/doobry/doobry-overlay.git'
         [aegypius]='https://github.com/aegypius/overlay.git')

echo "Please ignore 'fatal: remote %name% already exists.' messages"
for REMOTE in ${!REMOTES[@]}; do
	git remote add "${REMOTE}" "${REMOTES["${REMOTE}"]}"
	git pull -s subtree "${REMOTE}" "master"
done
